import { TypographyOptions } from '@mui/material/styles/createTypography';
import { fontStyleOptions } from './font-styles';
import { Palette } from '@mui/material';

export function constructVariants(palette: Palette): TypographyOptions {
  return {
    h1: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '6rem',
      lineHeight: '128px',
      letterSpacing: '-1.5px',
      color: palette.text.primary,
    },
    h2: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '3.75rem',
      lineHeight: '80px',
      letterSpacing: '0.5px',
      color: palette.text.primary,
    },
    h3: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '3rem',
      lineHeight: '64px',
      letterSpacing: '0px',
      color: palette.text.primary,
    },
    h4: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '2.125rem',
      lineHeight: '48px',
      letterSpacing: '0.25px',
      color: palette.text.primary,
    },
    h5: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '1.5rem',
      lineHeight: '32px',
      letterSpacing: '0px',
      color: palette.primary.main,
    },
    h6: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightBold,
      fontSize: '1.25rem',
      lineHeight: '26px',
      letterSpacing: '0.15px',
      color: palette.secondary.main,
    },
    subtitle1: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '1rem',
      lineHeight: '28px',
      letterSpacing: '0.15px',
      color: palette.secondary.main,
      textTransform: 'uppercase',
    },
    subtitle2: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightBold,
      fontSize: '0.875rem',
      lineHeight: '24px',
      letterSpacing: '0.1px',
      color: palette.text.primary,
      textTransform: 'uppercase',
    },
    body1: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '1rem',
      lineHeight: '24px',
      letterSpacing: '0px',
      color: palette.text.primary,
    },
    body2: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '0.875rem',
      lineHeight: '20px',
      letterSpacing: '0px',
      color: palette.text.primary,
    },
    button: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightBold,
      fontSize: '12px',
      lineHeight: '20px',
      letterSpacing: '1px',
      textTransform: 'uppercase',
      color: palette.text.primary,
    },
    caption: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '0.875rem',
      lineHeight: '20px',
      letterSpacing: '0px',
      color: palette.text.secondary,
    },
    overline: {
      fontFamily: fontStyleOptions.fontFamily,
      fontWeight: fontStyleOptions.fontWeightRegular,
      fontSize: '0.688rem',
      lineHeight: '20px',
      letterSpacing: '1.5px',
      color: palette.text.primary,
      textTransform: 'uppercase',
    },
  };
}
